spring.application.name=SightSeeingApp

server.port = 9090
#server.servlet.context-path=/product_manager_mljet

spring.datasource.url=jdbc:h2:file:./db/praksa;AUTO_SERVER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS SIGHTSEEING
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.hikari.schema=SIGHTSEEING
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=SIGHTSEEING
#spring.thymeleaf.cache=false
