GET http://localhost:9090/sightseeing-app/attractions/Zagreb
Accept: application/json

###

POST http://localhost:9090/sightseeing-app/attractions
Content-Type: application/json

{
  "location": {
    "name": "Zagreb"
  },
  "attractions": [
    {
      "name": "Muzej 1",
      "description": "Umjetnički muzej u Zagrebu",
      "type": "MUZEJ"
    }
  ]
}


###

PUT http://localhost:9090/product_manager_mljet/stores/Zagreb
Content-Type: application/json

{
  "location": {
    "name": "Zagreb"
  },
  "attractions": [
    {
      "name": "Muzej 2",
      "description": "Umjetnički muzej u Zagrebu",
      "type": "MUZEJ"
    },
    {
      "name": "Muzej Ivan",
      "description": "Umjetnički muzej u Zagrebu",
      "type": "MUZEJ"
    }
  ]
}
###
DELETE http://localhost:9090/sightseeing-app/attractions/Zagreb

###

POST http://localhost:9090/sightseeing-app/user
Content-Type: application/json

{
  "name": "Nikola Gordan",
  "email": "ngordan@tis.hr",
  "phoneNumber": "+385911234567",
  "dateOfBirth": "1980-12-01",
  "address": {
    "country": "HR",
    "city": "Split",
    "streetName": "Ljudevita Gaja",
    "houseNumber": "15A"
  }
}

